databases:
  - name: coffee-shop-db
    plan: free # Optional: specify your plan

services:
  # 1. Backend API Service (Python/FastAPI)
  - type: web
    name: coffee-shop-backend
    runtime: python
    rootDir: ./
    python: "3.11" # ✅ CORRECTED: Was 'pythonVersion'
    buildCommand: "pip install -r studio-main/src/requirements.txt"
    startCommand: "uvicorn studio-main.src.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: coffee-shop-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: coffee-shop-redis
          property: connectionString
      - key: ALLOWED_ORIGINS
        fromService:
          type: web
          name: coffee-shop-frontend
          property: url
      - key: TZ
        value: Asia/Kolkata

  # 2. Frontend Web Service (Next.js)
  - type: web
    name: coffee-shop-frontend
    runtime: node
    rootDir: ./studio-main
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        fromService:
          type: web
          name: coffee-shop-backend
          property: url

  # 3. Redis Service
  - type: redis
    name: coffee-shop-redis
    plan: free # Optional: specify your plan
