services:
  # PostgreSQL Database (for local development)
  postgres:
    image: postgres:15-alpine
    container_name: coffee_shop_postgres
    environment:
      - POSTGRES_DB=coffee_shop
      - POSTGRES_USER=coffee_user
      - POSTGRES_PASSWORD=coffee_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coffee_user -d coffee_shop"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: coffee_shop_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: coffee-shop-backend:latest
    container_name: coffee_shop_backend
    environment:
      - DATABASE_URL=postgresql://coffee_user:coffee_password@postgres:5432/coffee_shop
      - REDIS_URL=redis://redis:6379/0
      - SERVICE_API_KEY=sk-coffee-management-2024
      - API_KEY=sk-coffee-management-2024
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000/api
      - NEXT_PUBLIC_API_SERVER_URL=http://localhost:8000
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:9002
      - TZ=Asia/Kolkata
      - GOOGLE_SHEETS_CREDENTIALS_PATH=/app/credentials.json
      - GOOGLE_SHEET_ID=1HUumnzKXmZeg7TDQt7t5E87aPXHcGbyceYSf_mqmnq8
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - ./src:/app/src
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Next.js Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - NO_PROXY=${NO_PROXY}
    image: coffee-shop-frontend:latest
    container_name: coffee_shop_frontend
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - NO_PROXY=${NO_PROXY}
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000/api
      - NEXT_PUBLIC_API_SERVER_URL=http://localhost:8000
      - NEXT_PUBLIC_COIMBATORE_BRANCH_ID=1
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
  redis_data:
