[build]
  publish = ".next"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://coffee-shop-backend.onrender.com/api/:splat"
  status = 200

[build.environment]
  NEXT_PUBLIC_API_BASE_URL = "https://coffee-shop-backend.onrender.com/api"
  NEXT_PUBLIC_API_SERVER_URL = "https://coffee-shop-backend.onrender.com"
  NEXT_PUBLIC_COIMBATORE_BRANCH_ID = "1"
  NODE_ENV = "production"
