services:
  # Backend API Service
  - type: web
    name: coffee-shop-backend
    runtime: docker
    dockerfilePath: ./Dockerfile.backend
    buildCommand: pip install -r src/requirements.txt
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION # Use a stable Python version
        value: "3.11"
      - key: DATABASE_URL
        fromDatabase:
          name: coffee-shop-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: coffee-shop-redis
          property: host
      - key: SERVICE_API_KEY
        generateValue: true
      - key: API_KEY
        generateValue: true
      - key: TZ
        value: Asia/Kolkata
      - key: PYTHONUNBUFFERED
        value: 1

  # Frontend Web Service
  - type: web
    name: coffee-shop-frontend
    runtime: docker
    dockerfilePath: ./Dockerfile.frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        fromService:
          type: web
          name: coffee-shop-backend
          property: host
      - key: NEXT_PUBLIC_API_SERVER_URL
        fromService:
          type: web
          name: coffee-shop-backend
          property: host
      - key: NEXT_PUBLIC_COIMBATORE_BRANCH_ID
        value: "1"
      - key: NODE_ENV
        value: production

  # Scheduler Worker Service (for automation)
  - type: worker
    name: coffee-shop-scheduler
    runtime: docker
    dockerfilePath: ./Dockerfile.backend
    startCommand: python src/automation.py
    envVars:
      - key: PYTHON_VERSION # Use a stable Python version
        value: "3.11"
      - key: DATABASE_URL
        fromDatabase:
          name: coffee-shop-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: coffee-shop-redis
          property: host

  # Redis Service
  - type: redis
    name: coffee-shop-redis

  # PostgreSQL Database
  - type: psql
    name: coffee-shop-db
